### PR TITLE
Update package.json for Angular 10

### PR DESCRIPTION
**Pull request by clabough**

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hey, thanks for this! This change isn't actually needed though, the tslib peer dependency is already added by ng-packagr, if you take a look at the published package.json you can see it there: https://unpkg.com/browse/angular-confirmation-popover@5.0.0/package.json

If something isn't working on angular 10 though please let me know, thanks! 😄

**Comment by clabough** [comment]
@mattlewis92 I'm seeing this message from npm.

> angular-confirmation-popover@5.0.0 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

**Comment by mattlewis92** [comment]
Ah ok, it's so weird that none of my other packages are doing this and they all list tslib as a dependency, despite using the same tooling and all the same versions 🤔 I've fixed it here by just upgrading this one to v10 and cut a new release (`6.0.0`) so if you upgrade to that then it should get rid of that warning. Let me know if that works for you 😄

**Comment by clabough** [comment]
@mattlewis92 Thanks. That took care of it.

**Pull request closed without merging**
